#!/usr/bin/env python

import sys, getopt, urllib2

class ProxyDetector:
	def __init__(self):
		self.proxies = urllib2.getproxies()

	def get_proxy_config(self, key):
		if key in self.proxies:
			return self.proxies[key]
		else:
			return "none"

	def get_http_proxy(self):
		return self.get_proxy_config("http")

	def get_https_proxy(self):
		return self.get_proxy_config("https")
		

def main(argv):
	detector = ProxyDetector()
	protocol = ""

	try:
		opts, args = getopt.getopt(argv, "p:v", ['protocol'])
	except getopt.GetoptError as err:
		print str(err)
		sys.exit(2)

	for o, a in opts:
		if o in ("-p", "--protocol"):
			protocol = a.lower()

	if protocol == "":
		print "Missing protocol argument (-p): http or https"
		sys.exit(2)
	elif protocol == "http":
		print detector.get_http_proxy()
	elif protocol == "https":
		print detector.get_https_proxy()
	else:
		print "none"

if __name__ == "__main__":
	main(sys.argv[1:])
